---
name: Go package

on: [push]

env:
  MYSQL_TEST: true
  MYSQL_TEST_USER: 'dbuser'
  MYSQL_TEST_PASS: 'dbpass'
  MYSQL_TEST_HOST: '127.0.0.1:3306'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: start mysql
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: ${{ matrix.mysql }}
          user: ${{ env.MYSQL_TEST_USER }}
          password: ${{ env.MYSQL_TEST_PASS }}
      - name: create database
        run: |
          mysql --user 'root' --host '127.0.0.1' -e 'create database certs;'

      - name: Run tests
        run: |
          make test
          make lint

      - name: Build
        run: make
